site: Toby Aurelius
url: https://taurelius.github.io
title: Toby Aurelius
description: Software Developer
twitter:
  username: tobyaurelius
  card: summary
  creator: tobyaurelius
author:
  twitter: tobyaurelius
  name: Toby Aurelius
  avatar: https://avatars1.githubusercontent.com/u/22025115?v=2&s=200
  email: #youremail
  url: https://taurelius.github.io
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
theme: jekyll-theme-cayman
